name: dotoon_todo_app
description: "A new Flutter project."




version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  simple_gradient_text: ^1.3.0
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.0
  uuid:
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/pngs/
    - assets/
    - assets/images/

